server:
  port: 8050

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      finish-success: finish-success
      finish-fail: finish-fail
      orchestrator: orchestrator
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

logging:
  level.org.apache.kafka: OFF
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    patterntemplate: "[%p] %c{1}: %m%n"
  file:
    name: logs/service.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always